// This file is generated by Slice Machine. Update with care!

import BrandsMarquee from './BrandsMarquee'
import Careers from './Careers'
import ContentBlock from './ContentBlock'
import CopyBlock from './CopyBlock'
import Cta from './Cta'
import Gallery from './Gallery'
import Hexagons from './Hexagons'
import Image from './Image'
import ReorderCta from './ReorderCta'
import ScrollVideo from './ScrollVideo'
import Statistics from './Statistics'
import TriCycle from './TriCycle'

export {
  BrandsMarquee,
  Careers,
  ContentBlock,
  CopyBlock,
  Cta,
  Gallery,
  Hexagons,
  Image,
  ReorderCta,
  ScrollVideo,
  Statistics,
  TriCycle,
}

export const components = {
  brands_marquee: BrandsMarquee,
  careers: Careers,
  content_block: ContentBlock,
  copy_block: CopyBlock,
  cta: Cta,
  gallery: Gallery,
  hexagons: Hexagons,
  image: Image,
  reorder_cta: ReorderCta,
  scroll_video: ScrollVideo,
  statistics: Statistics,
  tri_cycle: TriCycle,
}
